import { z } from "zod";
import { requireRole, validateAdminMutation, authenticateAdminRequest } from "@/server/admin/auth";
import { db } from "@/server/shared/db";
import { requestId } from "@/server/security/http";
const Schema=z.discriminatedUnion("operation",[
z.object({operation:z.literal("store"),version:z.number().int().positive(),leadTimeMinutes:z.number().int().positive().max(240),minimumOrderKopecks:z.number().int().nonnegative().nullable(),legalBasis:z.enum(["CONTRACT","CONSENT"]),taxSystemCode:z.string().trim().min(1).max(40).nullable()}),
z.object({operation:z.literal("zone"),id:z.string().uuid().optional(),version:z.number().int().positive().optional(),name:z.string().trim().min(1).max(120),city:z.string().trim().min(1).max(120),feeKopecks:z.number().int().nonnegative(),freeThresholdKopecks:z.number().int().nonnegative().nullable(),minOrderKopecks:z.number().int().nonnegative().nullable(),isActive:z.boolean()}),
z.object({operation:z.literal("hours"),weekday:z.number().int().min(0).max(6),opensAt:z.string().regex(/^\d{2}:\d{2}$/).nullable(),closesAt:z.string().regex(/^\d{2}:\d{2}$/).nullable(),isClosed:z.boolean(),slotLength:z.number().int().positive().max(240),capacity:z.number().int().positive().nullable()}),
]);
export async function GET(request:Request):Promise<Response>{try{await authenticateAdminRequest(request);const[store,zones,hours,routing]=await Promise.all([db.storeSettings.findUnique({where:{id:"singleton"}}),db.deliveryZone.findMany({orderBy:{name:"asc"}}),db.operatingHours.findMany({orderBy:{weekday:"asc"}}),db.paymentRouting.findMany()]);return Response.json({store,zones,hours,routing},{headers:{"Cache-Control":"no-store"}})}catch{return new Response(null,{status:401})}}
export async function PATCH(request:Request):Promise<Response>{const id=requestId(request);try{const admin=await validateAdminMutation(request);requireRole(admin,["ADMIN"]);const parsed=Schema.safeParse(await request.json());if(!parsed.success)return Response.json({error:"validation"},{status:400});const result=await db.$transaction(async tx=>{let changed:unknown;if(parsed.data.operation==="store"){const{version}=parsed.data;const data={leadTimeMinutes:parsed.data.leadTimeMinutes,minimumOrderKopecks:parsed.data.minimumOrderKopecks,legalBasis:parsed.data.legalBasis,taxSystemCode:parsed.data.taxSystemCode};const count=await tx.storeSettings.updateMany({where:{id:"singleton",version},data:{...data,version:{increment:1}}});if(!count.count)return null;changed=await tx.storeSettings.findUnique({where:{id:"singleton"}})}else if(parsed.data.operation==="zone"){const zoneId=parsed.data.id,version=parsed.data.version;const data={name:parsed.data.name,city:parsed.data.city,feeKopecks:parsed.data.feeKopecks,freeThresholdKopecks:parsed.data.freeThresholdKopecks,minOrderKopecks:parsed.data.minOrderKopecks,isActive:parsed.data.isActive};if(zoneId){if(version===undefined)return null;const count=await tx.deliveryZone.updateMany({where:{id:zoneId,version},data:{...data,version:{increment:1}}});if(!count.count)return null;changed=await tx.deliveryZone.findUnique({where:{id:zoneId}})}else changed=await tx.deliveryZone.create({data})}else{const data={weekday:parsed.data.weekday,opensAt:parsed.data.opensAt,closesAt:parsed.data.closesAt,isClosed:parsed.data.isClosed,slotLength:parsed.data.slotLength,capacity:parsed.data.capacity};changed=await tx.operatingHours.upsert({where:{weekday:data.weekday},create:data,update:data})}await tx.adminAuditLog.create({data:{adminUserId:admin.id,action:"STORE_SETTINGS_UPDATED",targetType:parsed.data.operation,targetId:"id" in parsed.data&&parsed.data.id?parsed.data.id:String("weekday" in parsed.data?parsed.data.weekday:"singleton"),metadata:{operation:parsed.data.operation},requestId:id}});return changed});return result?Response.json(result):Response.json({error:"version_conflict"},{status:409})}catch{return new Response(null,{status:403})}}
